# Generated by Django 4.2.11 on 2024-05-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_customers'),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The first date the job should start (mm/dd/yyyy)')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks'), ('triweekly', 'Triweekly'), ('quadweekly', 'Quadweekly'), ('custom', 'Custom')], max_length=10)),
                ('custom_interval_days', models.IntegerField(blank=True, help_text='Number of days for custom frequency', null=True)),
                ('total_man_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('job_ordering', models.PositiveIntegerField(help_text="Order of the job in the day's schedule")),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instructions_for_crew', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='recurring_job_files/')),
                ('mow', models.BooleanField(default=False)),
                ('edge', models.BooleanField(default=False)),
                ('blow', models.BooleanField(default=False)),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.crew')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('total_man_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('job_ordering', models.PositiveIntegerField(help_text="Order of the job in the day's schedule")),
                ('instructions_for_crew', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='job_files/')),
                ('mow', models.BooleanField(default=False)),
                ('edge', models.BooleanField(default=False)),
                ('blow', models.BooleanField(default=False)),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.crew')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customers')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.proposal')),
            ],
        ),
    ]
