# Generated by Django 4.2.11 on 2024-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobschedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimejob',
            name='isscheduled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringjob',
            name='isscheduled',
            field=models.BooleanField(default=True),
        ),
    ]
