# Generated by Django 4.2.11 on 2024-05-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobschedules', '0002_onetimejob_isscheduled_recurringjob_isscheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringjob',
            name='gross_revenue',
        ),
    ]
