# Generated by Django 4.2.11 on 2024-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobschedules', '0004_jobs_remove_recurringjob_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks'), ('triweekly', 'Triweekly'), ('quadweekly', 'Quadweekly'), ('custom', 'Custom')], max_length=10, null=True),
        ),
    ]
