# Generated by Django 4.2.11 on 2024-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobschedules', '0005_alter_jobs_day_of_week_alter_jobs_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='recurring_end_date',
            field=models.DateField(blank=True, help_text='The first date the job should start (mm/dd/yyyy)', null=True),
        ),
    ]
